name: metadataSync
on:
  push:
    branches:
      - master
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Release to S3
      run: bash metadata/pipeline/release.sh ${{secrets.AWS_Bucket_Name}} "clinical/models/clinical_dummy_metadata.json" ${{secrets.AWS_Access_Key}} ${{secrets.AWS_Access_Secret}} "metadata/clinical_dummy_metadata.json"
      if: "contains(github.event.head_commit.message, '[metadata]')"
